# Generated by Django 6.0.2 on 2026-02-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('student_id', models.CharField(max_length=12, unique=True)),
                ('id_card', models.CharField(max_length=50, unique=True)),
                ('rfid_uid', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
