# Generated by Django 6.0.2 on 2026-02-22 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='session',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
