# Generated by Django 6.0.2 on 2026-03-15 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outingrequest',
            name='outing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outingrequest',
            name='outing_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
