# Generated by Django 6.0.2 on 2026-04-02 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_outingrequest_outing_date_outingrequest_outing_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id_card',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='rfid_uid',
            field=models.CharField(max_length=50),
        ),
    ]
