# Generated by Django 6.0.2 on 2026-03-02 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_student_course_student_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Out', 'Out'), ('Banned', 'Banned')], default='Pending', max_length=20),
        ),
    ]
