# Generated by Django 6.0.2 on 2026-04-02 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_student_id_card_alter_student_rfid_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id_card',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='rfid_uid',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
