# Generated by Django 6.0.2 on 2026-04-02 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_student_id_card_alter_student_rfid_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outingrequest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outing_requests', to='app.student'),
        ),
    ]
