# Generated by Django 6.0.2 on 2026-03-05 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_student_presence_status_checklog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklog',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_logs', to='app.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('None', 'None'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Banned', 'Banned')], default='None', max_length=20),
        ),
    ]
