# Generated by Django 6.0.2 on 2026-04-06 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_outingrequest_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outingrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Used', 'Used')], default='Pending', max_length=10),
        ),
    ]
