# Generated by Django 6.0.2 on 2026-06-23 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_outingrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='outingrequest',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outingrequest',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
