# Generated by Django 6.0.2 on 2026-07-04 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_outingrequest_rejected_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklog',
            name='is_late',
            field=models.BooleanField(default=False),
        ),
    ]
