# Generated by Django 6.0.2 on 2026-07-18 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_checklog_is_late'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outingrequest',
            name='rejected_at',
        ),
        migrations.RemoveField(
            model_name='outingrequest',
            name='rejection_reason',
        ),
    ]
