# Generated by Django 6.0.2 on 2026-03-15 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_student_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OutingRequest',
        ),
    ]
