# Generated by Django 6.0.2 on 2026-07-23 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_outingrequest_rejected_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_simulation_active', models.BooleanField(default=False, verbose_name='Enable Time Simulation')),
                ('simulated_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Simulated System Time')),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_contact',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Parent/Guardian Contact'),
        ),
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='student',
            name='tvetmara_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='TVETMARA E-MAIL'),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(max_length=100, verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='id_card',
            field=models.CharField(max_length=50, unique=True, verbose_name='IC Number'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='rfid_uid',
            field=models.CharField(max_length=50, unique=True, verbose_name='RFID UID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='session',
            field=models.CharField(max_length=20, verbose_name='Session'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=12, unique=True, verbose_name='Matric ID'),
        ),
    ]
