# Generated by Django 6.0.2 on 2026-08-14 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_systemsettings_student_address_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SystemSettings',
        ),
    ]
