# Generated by Django 6.0.2 on 2026-09-25 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_outingtimesettings_curfew_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='student_photos/', verbose_name='Profile Picture'),
        ),
    ]
