# Generated by Django 6.0.2 on 2026-09-28 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_staffprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklog',
            name='warning_sent',
            field=models.BooleanField(default=False),
        ),
    ]
