# Generated by Django 6.0.2 on 2026-09-30 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_checklog_warning_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklog',
            name='outing_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_logs', to='app.outingrequest'),
        ),
        migrations.AddField(
            model_name='outingrequest',
            name='request_type',
            field=models.CharField(choices=[('Outing', 'Outing'), ('Home Leave', 'Home Leave')], default='Outing', max_length=20),
        ),
        migrations.AddField(
            model_name='outingrequest',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outingtimesettings',
            name='max_home_leave_days',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
